import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'
import styles from '../styles/Home.module.css';

export default function Home(){
  return (
    <>  
      <Layout pageTitle='Home'>
        <Image src="/logo.jpeg" width={200} height={200} alt="logo"/>
        <h1 className={styles['title-homepage']}>welcome dani</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <Image src="/logo2.png" width={200} height={200} alt="logo" />
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam necessitatibus optio corporis harum error, aut praesentium cum ipsam et nihil aliquam, sint quo labore consectetur quidem animi natus officiis exercitationem!</p>
      </Layout>
    </>

  );
}
